services:
  - type: web
    name: vendeagil-app
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
